Repository oconva/qvikchat, pull requests merged in 2024-07, with the labels that each got.

#1 Bumping the NPM package version
  package-lock.json
  package.json
Labels: documentation

#3 updated data retriever - removed dependency on path
  src/rag/data-retrievers/data-retrievers.ts
Labels: bug

#6 Updated documentation
  README.md
Labels: documentation

#8 Fix for supporting chat history with RAG chat + changes to defineChatEndpoint
  README.md
  package-lock.json
  package.json
  src/endpoints/endpoints.ts
  src/prompts/chat-prompts.ts
  src/prompts/system-prompts.ts
  src/tests/endpoint-rag.tests.ts
Labels: bug, documentation, enhancement

#10 Endpoint agent config
  package-lock.json
  package.json
  src/endpoints/endpoints.ts
  src/genkit/genkit.ts
  src/tests/endpoint-agent.tests.ts
  src/utils/utils.ts
Labels: enhancement

#11 Update build.yml workflow
  .github/workflows/build.yml
Labels: enhancement

#13 Added CodeQL workflow for code scanning
  .github/workflows/codeql.yml
Labels: enhancement

#16 Fix issue 15 - Unable to continue chat when cache is enabled
  .github/workflows/codeql.yml
  src/endpoints/endpoints.ts
  src/prompts/system-prompts.ts
  src/tests/endpoint-close-ended.tests.ts
  src/tests/endpoint-rag.tests.ts
  src/tests/integration-tests/endpoint.int.test.ts
  src/tests/unit-tests/endpoint-agent.unit.test.ts
  src/tests/unit-tests/endpoint-api-keys.unit.test.ts
  src/tests/unit-tests/endpoint-cache.unit.test.ts
  src/tests/unit-tests/endpoint-chat-history.unit.test.ts
  src/tests/unit-tests/endpoint-close-ended.unit.test.ts
  src/tests/unit-tests/endpoint-rag.unit.test.ts
Labels: bug

#17 Fix issue 15 - Unable to continue chat when cache is enabled (#15)
  package-lock.json
  package.json
Labels: bug

#29 Data loader 28
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/publish-npm.yml
  .prettierrc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  eslint.config.mjs
  jest.config.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/agents/chat-agent.ts
  src/auth/api-key-auth-policy.ts
  src/auth/api-key-store.ts
  src/auth/firestore-api-key-store.ts
  src/auth/in-memory-api-key-store.ts
  src/cache/cache-store.ts
  src/cache/firestore-cache-store.ts
  src/cache/in-memory-cache-store.ts
  src/config/config.ts
  src/endpoints/endpoints.ts
  src/genkit/genkit.ts
  src/history/chat-history-store.ts
  src/history/firestore-chat-history-store.ts
  src/history/in-memory-chat-history-store.ts
  src/integrations/firebase/firebase.ts
  src/models/models.ts
  src/prompts/README.md
  src/prompts/chat-prompts.ts
  src/prompts/prompts.ts
  src/prompts/system-prompts.ts
  src/rag/data-embeddings/embedding-models.ts
  src/rag/data-loaders/data-loaders.ts
  src/rag/data-retrievers/data-retrievers.ts
  src/rag/data-splitters/data-splitters.ts
  src/tests/integration-tests/endpoint.int.test.ts
  src/tests/unit-tests/endpoint-agent.unit.test.ts
  src/tests/unit-tests/endpoint-api-keys.unit.test.ts
  src/tests/unit-tests/endpoint-cache.unit.test.ts
  src/tests/unit-tests/endpoint-chat-history.unit.test.ts
  src/tests/unit-tests/endpoint-close-ended.unit.test.ts
  src/tests/unit-tests/endpoint-rag.unit.test.ts
  src/utils/utils.ts
Labels: enhancement

#32 Changes to make `dataType` optional + fix for peer dependencies
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/rag/data-loaders/data-loaders.ts
  src/rag/data-retrievers/data-retrievers.ts
  src/tests/integration-tests/endpoint.int.test.ts
Labels: bug, enhancement

#34 Fix for the issue where `filePath` was still required when providing `docs` in retriever config #33
  package-lock.json
  package.json
  src/rag/data-loaders/data-loaders.ts
  src/rag/data-retrievers/data-retrievers.ts
  src/tests/unit-tests/endpoint-rag.unit.test.ts
Labels: bug

#57 Added Changes to prompts, chat agent, endpoints to support Multimodal I/O
  package.json
  src/agents/chat-agent.ts
  src/endpoints/endpoints.ts
  src/models/models.ts
  src/prompts/README.md
  src/prompts/chat-prompts.ts
  src/prompts/prompts.ts
  src/prompts/system-prompts.ts
Labels: enhancement

#59 Fixed issues with basic system prompt + added default system prompts #43
  package-lock.json
  package.json
  src/agents/chat-agent.ts
  src/prompts/chat-prompts.ts
  src/prompts/system-prompts.ts
  src/tests/unit-tests/endpoint-agent.unit.test.ts
Labels: bug, enhancement

#60 Multimodal fix - multiple changes to chat agent module to support multimodal I/O
  package.json
  src/agents/chat-agent.ts
  src/endpoints/endpoints.ts
  src/index.ts
  src/models/models.ts
  src/tests/unit-tests/endpoint-agent.unit.test.ts
Labels: bug, enhancement

#63 Models patch - fixes for multimodal support + implementation of `configureAndRunServer` method #43 #54
  package.json
  pnpm-lock.yaml
  src/config/config.ts
  src/core/core.ts
  src/index.ts
  src/models/models.ts
  src/tests/integration-tests/endpoint.int.test.ts
  src/tests/unit-tests/endpoint-agent.unit.test.ts
  src/tests/unit-tests/endpoint-api-keys.unit.test.ts
  src/tests/unit-tests/endpoint-cache.unit.test.ts
  src/tests/unit-tests/endpoint-chat-history.unit.test.ts
  src/tests/unit-tests/endpoint-close-ended.unit.test.ts
  src/tests/unit-tests/endpoint-rag.unit.test.ts
Labels: bug, enhancement
